### ISSUE TITLE
Refine GALP5 fan curves + add support for GPU fan

### ISSUE THREAD

**Issue by ZeddieXX** [system76/ec#140] opened 2021-01-20 19:24 UTC
For non DGPU GALP5, the 2nd fan never kicks on.  For those who did not get a DGPU, can we make it functional?  By enabling the DGPU fan for CPU-only GALP5, fan speeds can remain slower longer (less noise).  We should add more points to smooth out the abrupt fan noise when it ramps up and down, too.

Of course this might mean we'll need a different firmware just for CPU-only GALP5s vs GPU+CPU GALP5s.

**Comment by leviport** [comment] 2021-01-20 19:27
Duplicate of https://github.com/system76/firmware-open/issues/148

**Closed by leviport** 2021-01-20 19:27 UTC
